class OperationProvider:
    @staticmethod
    def get_operations():
        return ['[DOCUMENTO PENDENTE POSITIVO]', '[ERRO DE CODIFICACAO POSITIVO]', '[ERRO DE MULTIPLO POSITIVO]', '[NOTA FISCAL POSITIVA]', '[BRINDES]', '[DANIFICADOS]', '[DOCUMENTO PENDENTE NEGATIVO]', '[ERRO DE CODIFICACAO NEGATIVO]', '[ERRO DE MULTIPLO NEGATIVO]', '[FURTO]', '[NOTA FISCAL NEGATIVA]', '[VENCIDO NA LOJA]', '[VENCIDOS DO FORNECEDOR]', '[OUTRAS SAIDAS A PRECO CUSTO]', '[TRANSFERENCIA]', '[VENDA SUMIRE A CUSTO]']
